export default {
    "advanced": {
        "Timeline Playhead": "The playhead in the timeline while the track is playing.",
    },
    "window": {
        "Abstract Button Pressed Background": "",
        "Abstract Button Selected Background": "",
        "Abstract Button Stroke": "",
        "Abstract Button Unselected Background": "",
        "Activation Green": "Status of Activation inside \"Manage Licenses\" popup.",
        "Activation Red": "Status of Activation inside \"Manage Licenses\" popup.",
        "Activation Yellow": "Status of Activation inside \"Manage Licenses\" popup.",
        "Active Inverted Toggle Icon (Playing)": "",
        "Active Panel stroke": "Border of active (selected) panel of the UI. E.g. arranger, browser, etc.",
        "Active Toggle Icon (Playing)": "",
        "Analyzed Beat Color": "",
        "Audio Event Boundary": "Boundaries of audio event in clip view.",
        "Automation Color": "",
        "Beat Marker Color": "Manually added beat markers (inverted when the beat marker is selected)",
        "Bitwig 16-Track": "",
        "Bitwig 8-Track": "",
        "Bitwig CI": "",
        "Bitwig Essentials": "",
        "Bitwig Mint": "This color is used in the circle that flashes in the top right corner of the screen when a project loads.",
        "Bitwig Producer": "",
        "Bitwig Red": "",
        "Button background": "All default buttons colors (transport etc.)",
        "Button in tree background": "",
        "Button stroke": "Buttons border",
        "Checkbox background": "",
        "Close button mouse over background": "",
        "Close button pressed background": "",
        "Comp fill": "",
        "Content Background": "",
        "Dark Panel Sub-frame Fill": "",
        "Dark Panel Sub-frame Stroke": "",
        "Dark Separator Line": "",
        "Dark Text": "Main black text color.",
        "Dark tree background (selected)": "The selected entry in the right-side browser when panel is focussed.",
        "Dark tree background (standby selected)": "The selected entry in the right-side browser when panel is not focussed.",
        "Dark tree hover background change": "",
        "Dark tree separator": "",
        "Dark tree text": "",
        "Dark tree text (selected)": "",
        "Default text": "",
        "Device Header": "",
        "Device Header (selected)": "",
        "Device Locked Overlay": "",
        "Device Tint Future": "",
        "Device Tint Military": "",
        "Device Tint Retro": "",
        "Display Background": "Changes the background of all display elements, for example in the sampler, the transport details, and some elements in the inspector - Also changes one of the 2 colors that make the gradients of various devices (such as sampler and comp+)",
        "Display Background (error)": "",
        "Display Loop Markers": "",
        "Display Start/End Markers": "",
        "Display Waveform": "",
        "Drop Indicator": "",
        "Emboss Highlight": "",
        "Emboss Shadow": "",
        "Error Text": "",
        "Field background": "",
        "Grey Display Background": "",
        "Grid Line (Primary)": "",
        "Grid Line (Secondary)": "",
        "Hitcount background": "",
        "Hitcount text color": "",
        "Hitech background": "",
        "Hitech on": "The transport color, as well as the blue text on the right-side panel.",
        "Hole (dark)": "Seemingly affects all major background spaces such as background of the tracks / scenes, background of the device pane and background of browsers.",
        "Hole (light)": "Affects smaller background elements.",
        "Hole (medium)": "Affects other smaller background elements.",
        "Implicit On (subtle)": "",
        "Inspector Section Frame": "",
        "Inverted Selected Borderless Button background": "",
        "Knob Body Darkest": "The body of dark knobs.",
        "Knob Body Lighter": "The body of lighter knobs",
        "Knob Body Lightest": "The body of the lightest / white knobs",
        "Knob Emboss Highlight": "",
        "Knob Emboss Shadow": "",
        "Knob Line": "The knob pointer on dark knobs.",
        "Knob Line Dark": "The knob pointer on light knobs.",
        "Knob Stroke": "The stroke around the knob.",
        "Knob Value Color": "The main colored value for a knob.",
        "Launcher Mapping Indication": "",
        "Led Off": "",
        "Led On": "",
        "Light Separator Line": "",
        "Light Text": "Main white text color.",
        "Light Tooltip Background": "",
        "Lighter Text": "",
        "Link Text": "",
        "List Item Background": "",
        "List Separator": "",
        "Mapping": "",
        "Mapping indication 1": "These are the coloured indicators that appear above remote controls when you're using a capable MIDI controller.",
        "Mapping indication 2": "These are the coloured indicators that appear above remote controls when you're using a capable MIDI controller.",
        "Mapping indication 3": "These are the coloured indicators that appear above remote controls when you're using a capable MIDI controller.",
        "Mapping indication 4": "These are the coloured indicators that appear above remote controls when you're using a capable MIDI controller.",
        "Mapping indication 5": "These are the coloured indicators that appear above remote controls when you're using a capable MIDI controller.",
        "Mapping indication 6": "These are the coloured indicators that appear above remote controls when you're using a capable MIDI controller.",
        "Mapping indication 7": "These are the coloured indicators that appear above remote controls when you're using a capable MIDI controller.",
        "Mapping indication 8": "These are the coloured indicators that appear above remote controls when you're using a capable MIDI controller.",
        "Medium Light Text": "",
        "Menu Icon": "",
        "Menu background": "",
        "Menu description text": "",
        "Menu separator": "",
        "Menu stroke": "",
        "Menu text": "",
        "Meter Clipping": "The highest value in a meter (clipping)",
        "Meter Gain Reduction": "",
        "Meter Hitech": "CPU/IO Meter colors",
        "Meter Hitech Background": "Background of CPU/IO Meter color",
        "Meter Muted": "",
        "Meter Normal": "The lowest value in a meter",
        "Meter Red": "The second highest value in a meter",
        "Meter Yellow": "The second lowest value in a meter",
        "Modern Dark Scrollbar Handle (active)": "",
        "Modern Dark Scrollbar Handle (inactive)": "",
        "Modern Scrollbar Background (active)": "Color of browser and devices panel scrollbars when hovered.",
        "Modern Scrollbar Handle (active)": "Color of browser scrollbars and devices panel handle when hovered.",
        "Modern Scrollbar Handle (inactive)": "",
        "Modulation Mapping Background (polyphonic)": "",
        "Modulation Mapping Background Color": "",
        "Modulation Mapping Color": "",
        "Modulation Mapping Color (polyphonic)": "",
        "Modulation Mapping Color (subtractive)": "",
        "Monitoring buttons color": "The Solo button",
        "Mouse Over Inverted Toggle Icon": "",
        "Mouse Over Toggle Icon": "",
        "Normal Inverted Toggle Icon": "",
        "Normal Toggle Icon": "",
        "Notification Background": "Background of top right notification (when loading projects, etc.)",
        "Notification Error": "Text color for the notifications when there is an error.",
        "Notification Normal": "Text color for notifications",
        "Number field bar background": "",
        "On": "The \"main\" orange button color (for Play, Mute etc). Probably, this also affects the color of the track volume faders.",
        "On (subtle)": "",
        "On (subtler)": "",
        "Onset Marker Color": "",
        "Panel Blue": "This colors starting with \"Panel...\" are responsible for the colors of the connection lines in the Grid. These also affect various colors in all devices (knobs, displays etc.)",
        "Panel Green": "This colors starting with \"Panel...\" are responsible for the colors of the connection lines in the Grid. These also affect various colors in all devices (knobs, displays etc.)",
        "Panel Lime": "This colors starting with \"Panel...\" are responsible for the colors of the connection lines in the Grid. These also affect various colors in all devices (knobs, displays etc.)",
        "Panel Mint": "This colors starting with \"Panel...\" are responsible for the colors of the connection lines in the Grid. These also affect various colors in all devices (knobs, displays etc.)",
        "Panel Orange": "This colors starting with \"Panel...\" are responsible for the colors of the connection lines in the Grid. These also affect various colors in all devices (knobs, displays etc.)",
        "Panel Purple": "This colors starting with \"Panel...\" are responsible for the colors of the connection lines in the Grid. These also affect various colors in all devices (knobs, displays etc.)",
        "Panel Red": "This colors starting with \"Panel...\" are responsible for the colors of the connection lines in the Grid. These also affect various colors in all devices (knobs, displays etc.)",
        "Panel Turquoise": "This colors starting with \"Panel...\" are responsible for the colors of the connection lines in the Grid. These also affect various colors in all devices (knobs, displays etc.)",
        "Panel Yellow": "This colors starting with \"Panel...\" are responsible for the colors of the connection lines in the Grid. These also affect various colors in all devices (knobs, displays etc.)",
        "Panel body": "Affects the main background of most elements, including devices and track background colors - This is also overlayed on top of the buttons in BW's top bar, so it also affects them. A darker color will also make the buttons darker.",
        "Panel stroke": "Border of most elements, also the main UI (it's basically the color for separating sections of the UI).",
        "Popup Notification Background": "",
        "Popup insert": "",
        "Popup overlay background color": "",
        "Pressed Inverted Toggle Icon": "",
        "Pressed On": "Same as \"On\" but when mouse is clicked and held. Makes sense to use a darker variant of the color used for \"On\"",
        "Pressed Toggle Icon": "",
        "Pressed button background": "",
        "Pressed view button background": "",
        "Progress background": "Background of progress bar (in notifications, not sure if anywhere else)",
        "Progress bar": "Color fill of progress bar",
        "Record button color": "This is obviously the record button color, but also the automation write and overdub buttons next to it. It also affects the dark red of the overdub button when it's on (but recording is off)",
        "Rubber button stroke": "",
        "Rubber highlight button stroke": "",
        "Scrollbar": "Color of arranger area scrollbar.",
        "Scrollbar background": "",
        "Selected Dashboard Tree": "",
        "Selected Panel body": "Background of selected track in arranger (not sure if also somewhere else)",
        "Selected Panel stroke": "",
        "Selected Panel stroke (standby)": "",
        "Selection": "",
        "Shadow": "A shadow that is added if the tracks extend beyond the displayed area.",
        "Standby selection": "",
        "Subtle Dark Text": "",
        "Subtle Light Text": "",
        "Subtler Light Text": "",
        "The Grid (background)": "The squares in the grid",
        "The Grid (stroke)": "The lines between squares in the grid",
        "Timeline edit tool chooser background": "",
        "Tooltip Background": "",
        "Tooltip Stroke": "",
        "Tree Item Background": "",
        "Tree Separator": "",
        "User Automation Override Color": "The color of the icon when manually overriding automation (Has a uneditable slight gradient on the icon to give it a slight bump). And also the color of the dot next to the parameter on devices.",
        "View button background": "",
        "Warning": "",
        "Window background": "Window background color (the very top bar color etc.)"
    },
    "arranger": {
        "Add Modulation Button Color": "Button that switches to additive modulation mode in the edit window.",
        "Audio connection in modular environment": "",
        "Audio64 connection in modular environment": "",
        "Automation button glow color": "",
        "Background color of the modular environment.": "",
        "Clip Automation Button Color": "",
        "Clip Automation Color": "",
        "Clip Modulation Color": "",
        "Compressed Audio Port in modular environment": "",
        "Current Atom Value Color": "Automation line when no automation is present (no nodes)",
        "Dark Timeline Background": "This is the unused portion of the arranger.",
        "Dark Timeline Header Background": "Background of the timeline on top of the arranger (90% sure)",
        "Event connection in modular environment": "",
        "Header Loop Region Background": "",
        "Header Time Selection Across All Lanes Fill": "",
        "Header Time Selection Across All Lanes Stroke": "",
        "Header Time Selection Cursor Stroke": "",
        "Header Time Selection Fill": "",
        "Header Time Selection Standby Cursor Stroke": "",
        "Header Time Selection Standby Fill": "",
        "Header Time Selection Standby Stroke": "",
        "Header Time Selection Stroke": "",
        "Insert preview time": "",
        "Irrelevant Timeline Background": "",
        "Irrelevant Timeline Header Background": "",
        "Irrelevant Timeline Header Overlay": "",
        "Irrelevant Timeline Overlay": "",
        "Light Timeline Background": "",
        "Light Timeline Header Background": "",
        "Loop Region Background": "",
        "Multiply Modulation Button Color": "Button that switches to multiply modulation mode in the edit window. Next to \"Add Modulation Button Color\"",
        "Note Expression Color": "",
        "Polyphonic Desktop Object": "",
        "Record button color implicit": "",
        "Record button glow color": "",
        "Selected matrix slot color": "",
        "Send (post) value color": "Knob color for send value in Post mode",
        "Send (pre) value color": "Knob color for send value in Pre mode",
        "Time Selection Across All Lanes Fill": "",
        "Time Selection Across All Lanes Stroke": "",
        "Time Selection Cursor Stroke": "",
        "Time Selection Fill": "",
        "Time Selection Inactive Fill": "",
        "Time Selection Inactive Stroke": "",
        "Time Selection Not Selected Fill": "",
        "Time Selection Not Selected Stroke": "",
        "Time Selection Standby Cursor Stroke": "",
        "Time Selection Standby Fill": "",
        "Time Selection Standby Stroke": "",
        "Time Selection Stroke": "",
        "Timeline Background Pattern": "Darkens black key area on piano roll background",
        "Timeline Cue Marker": "",
        "Timeline Header Background Pattern": "",
        "Timeline Header Cue Marker": "",
        "Timeline Header Primary Grid": "",
        "Timeline Header Secondary Grid": "",
        "Timeline Header Tooltip Background": "",
        "Timeline Header Tooltip Text": "",
        "Timeline Primary Grid": "",
        "Timeline Secondary Grid": "",
        "Timeline Tooltip Background": "",
        "Timeline Tooltip Text": "",
        "Top Level Timeline Background": "",
        "Top Level Timeline Header Background": "",
        "Track Automation Button Color": "Indicator that automation is active on a parameter.",
        "Track Automation Color": "The background and points of automation."
    }
}